
/* ---------- NUTRIÇÃO ---------- */
var NUTRI = {
  intro: "Orientações gerais para quem treina 5 dias por semana e quer perder gordura sem perder músculo. Não substitui uma nutricionista: se tiveres alguma condição de saúde, fala com ela primeiro.",
  sections: [
    {key:"base", name:"Princípios", cards:[
      {t:"Défice pequeno, não fome", b:"Para perder gordura e manter o músculo, comes um pouco menos do que gastas, não muito menos. Uma referência: 300 a 500 kcal abaixo do que precisas por dia. Mais do que isso e o corpo começa a gastar músculo e a energia no treino cai. Objetivo saudável: 0,3 a 0,5 kg por semana."},
      {t:"Proteína em todas as refeições", b:"É o que protege o músculo quando estás em défice e o que mais sacia. Para 57 kg e treino forte: 100 a 115 g de proteína por dia, repartidos por 3 a 4 refeições de 25 a 35 g. Fontes: ovos, frango, peru, peixe, atum, iogurte grego, queijo fresco, skyr, tofu, lentilhas, grão."},
      {t:"Hidratos à volta do treino", b:"Não cortes os hidratos: são o combustível dos WODs e das superséries. Põe a maior parte antes e depois do treino (aveia, arroz, batata, batata-doce, fruta, pão integral) e nas outras refeições dá prioridade a legumes e proteína."},
      {t:"Gordura boa, em quantidade moderada", b:"Azeite, azeitonas, abacate, frutos secos, sementes, peixe gordo. Faz falta às hormonas e à saciedade, mas é densa em calorias: 1 colher de sopa de azeite são ~120 kcal. Mede em vez de despejar."},
      {t:"Legumes a encher metade do prato", b:"Volume, fibra e poucas calorias. Metade do prato de legumes ou salada ao almoço e ao jantar é a forma mais fácil de comer menos sem sentir."},
      {t:"Consistência > perfeição", b:"Não há alimentos proibidos. O que conta é o que fazes 80% do tempo. Uma refeição fora do plano não estraga a semana; o que estraga é desistir por causa dela."}
    ]},
    {key:"dia", name:"O dia", cards:[
      {t:"Pequeno-almoço", b:"Proteína + hidrato lento + fruta. Ex.: iogurte grego com aveia e fruta, ovos mexidos com pão integral, papas de aveia com whey. Se treinas de manhã cedo, pode ser mais leve (ver «Antes do treino»)."},
      {t:"Almoço e jantar", b:"A regra do prato: ½ legumes ou salada, ¼ proteína (uma palma da mão, 120 a 150 g), ¼ hidrato (um punho: arroz, massa, batata, leguminosas). Azeite 1 colher de sopa no total."},
      {t:"Snacks", b:"Só se tiveres fome ou quando o intervalo entre refeições passa de 4 a 5 horas. Bons snacks: iogurte grego ou skyr, fruta com um punhado de frutos secos, queijo fresco, ovo cozido, húmus com cenoura, tosta integral com atum."},
      {t:"Água", b:"2 a 2,5 litros por dia, mais 500 ml nos dias de treino. Um copo grande ao acordar e uma garrafa sempre por perto. Sede confunde-se muitas vezes com fome."},
      {t:"Dia de descanso", b:"Nos dias sem treino, mantém a proteína e reduz um pouco os hidratos (menos arroz ou pão, mais legumes). Não é preciso «compensar» nem passar fome."},
      {t:"Sono", b:"7 a 8 horas. Dormir mal aumenta a fome no dia seguinte (sobretudo de doces) e piora a recuperação. Faz parte do plano tanto como o treino."}
    ]},
    {key:"treino", name:"Antes e depois", cards:[
      {t:"1 a 2 h antes do treino", b:"Refeição normal com hidrato e proteína, pouca gordura (digere mais devagar). Ex.: arroz com frango e legumes, pão integral com ovos, papas de aveia com iogurte."},
      {t:"30 a 45 min antes", b:"Se não comeste há mais de 3 horas: algo leve e rápido, 1 banana, 2 tâmaras, uma tosta com compota, um iogurte com mel. Nos treinos de manhã cedo em jejum, um café e uma banana chegam para WODs curtos; para treinos de força longos, come."},
      {t:"Nos 60 min depois", b:"Proteína (25 a 35 g) + hidrato. É quando o músculo mais aproveita. Ex.: batido de whey com banana e aveia, iogurte grego com granola e fruta, wrap de frango, arroz com atum. Não precisa de ser imediato, mas não deixes passar horas."},
      {t:"Café e pré-treino", b:"Um café 30 a 60 min antes ajuda a energia e o foco nos WODs. Bebidas energéticas e pré-treinos em pó não são precisos; se usares, evita depois das 16h para não estragar o sono."},
      {t:"Suplementos que fazem sentido", b:"Whey (proteína prática, não obrigatória), creatina (3 a 5 g por dia, todos os dias, ajuda força e recuperação; é dos poucos com muita evidência), vitamina D no inverno. O resto é dispensável."},
      {t:"Sinais de que estás a comer pouco", b:"Pesos a descer semana após semana, cansaço permanente, sono mau, fome de noite, irritação. Se acontecer, sobe 200 a 300 kcal (hidratos à volta do treino) durante uma semana e vê como reages."}
    ]},
    {key:"dicas", name:"Dicas", cards:[
      {t:"Prepara ao domingo", b:"Cozinha 2 proteínas (frango, ovos cozidos, atum), 1 hidrato (arroz, batata-doce, quinoa) e lava/corta legumes. Em 15 minutos montas as refeições da semana."},
      {t:"Come devagar", b:"Pousa os talheres entre garfadas, mastiga bem. O sinal de saciedade demora 15 a 20 minutos a chegar ao cérebro. Comer devagar faz comer menos sem esforço."},
      {t:"Começa pelos legumes", b:"Salada ou sopa primeiro, depois o resto. Chegas ao hidrato com menos fome."},
      {t:"Doces", b:"Se apetecer, come 1 quadrado de chocolate negro (70%+), um iogurte com canela, fruta congelada triturada ou uma das receitas doces daqui. Proibir totalmente costuma acabar em exagero."},
      {t:"Fora de casa", b:"Escolhe grelhados, peixe, saladas com proteína, sopa. Pede o molho à parte. Um copo de vinho está bem, o segundo já pesa (~120 kcal cada)."},
      {t:"Bebidas", b:"Água, café, chá, infusões e água com gás com limão são livres. Sumos, refrigerantes e cerveja são calorias que não saciam. Um café com leite ok; um cappuccino de 400 ml com xarope é uma sobremesa."},
      {t:"Pesa-te bem", b:"Uma vez por semana, de manhã, depois do WC, em jejum, sem roupa. O peso oscila 1 a 2 kg por dia com água, sal e ciclo. Olha para a tendência do mês, não para um dia. Fotos e roupa dizem tanto como a balança."},
      {t:"Álcool", b:"Trava a queima de gordura enquanto o corpo o processa e piora o sono. Se beberes, planeia: 1 a 2 copos, água pelo meio, e não num dia de treino pesado."}
    ]}
  ],
  supplements: [
    {t:"Whey (proteína em pó)", tag:"Prático", lvl:"ok", dose:"1 scoop (25–30 g de proteína)", when:"Nos 60 min depois do treino, ou em qualquer refeição em que falte proteína (pequeno-almoço, snack).", b:"Não é obrigatória: é só uma forma rápida de chegar aos 100–115 g de proteína por dia. Whey isolada digere melhor se o leite te cair mal. Sem whey: iogurte grego, skyr ou ovos fazem o mesmo trabalho."},
    {t:"Creatina monohidratada", tag:"Vale a pena", lvl:"ok", dose:"3 a 5 g por dia, todos os dias (não é preciso fase de carga)", when:"A qualquer hora, sempre à mesma. Mais fácil misturada no batido pós-treino ou no iogurte.", b:"É o suplemento com mais evidência para força, potência e recuperação, e ajuda também a concentração. Pode subir 0,5 a 1 kg na balança nas primeiras semanas (é água dentro do músculo, não gordura). Bebe água suficiente. Efeito demora 2 a 4 semanas a notar."},
    {t:"Cafeína", tag:"Vale a pena", lvl:"ok", dose:"1 café (60–100 mg) a 2 cafés antes do treino; máximo 200 mg de uma vez", when:"30 a 60 minutos antes do treino. Nunca depois das 15–16h, para não estragar o sono.", b:"Melhora energia, foco e tolerância ao esforço nos WODs e nos treinos pesados. Um expresso chega; não precisas de pré-treino em pó. Se ficares nervosa ou com o coração acelerado, reduz."},
    {t:"Vitamina D3", tag:"Vale a pena no inverno", lvl:"ok", dose:"1000 a 2000 UI por dia", when:"De manhã, com uma refeição que tenha gordura (absorve melhor).", b:"Entre outubro e março a maioria das pessoas em Portugal fica abaixo do ideal, e a vitamina D pesa na força, na imunidade e no humor. Pede à médica para medir nas análises: se estiver bem, não precisas."},
    {t:"Ómega-3 (EPA/DHA)", tag:"Opcional", lvl:"opt", dose:"1 a 2 g de EPA+DHA por dia (vê o rótulo: não é o peso da cápsula)", when:"Com uma refeição principal, para não repetir.", b:"Só faz falta se comeres peixe gordo (salmão, sardinha, cavala) menos de 2 vezes por semana. Ajuda à recuperação e à saúde cardiovascular. Guarda no frigorífico."},
    {t:"Magnésio", tag:"Opcional", lvl:"opt", dose:"200 a 400 mg (bisglicinato ou citrato; evita óxido, que absorve mal)", when:"À noite, 30 a 60 min antes de deitar.", b:"Pode ajudar em cãibras, sono e recuperação, sobretudo com muito treino e pouca fruta, legumes e frutos secos. Se comeres bem disso tudo, provavelmente não precisas."},
    {t:"Eletrólitos", tag:"Só em dias específicos", lvl:"opt", dose:"1 saqueta ou 1/4 de colher de chá de sal em 500 ml de água", when:"Em treinos longos (mais de 60–75 min) com muito suor, ou em dias de calor.", b:"Para treinos de 40 minutos com ar condicionado, água chega. Não precisas de bebidas isotónicas com açúcar."},
    {t:"Multivitamínico", tag:"Opcional", lvl:"opt", dose:"1 por dia, dose baixa", when:"Com o pequeno-almoço.", b:"Uma rede de segurança em fases de défice calórico, quando se come menos volume. Não substitui legumes e fruta. Escolhe um com ferro só se as análises mostrarem falta."},
    {t:"Colagénio", tag:"Pouca evidência", lvl:"no", dose:"10–15 g com vitamina C", when:"30–60 min antes do treino, se quiseres experimentar.", b:"Há alguma evidência para tendões e articulações, pouca para pele. Não é prioridade: com a proteína diária bem feita, o corpo tem o que precisa."},
    {t:"BCAAs e glutamina", tag:"Não precisas", lvl:"no", dose:"—", when:"—", b:"Se a proteína diária estiver no sítio, os BCAAs já lá estão. É dinheiro deitado fora."},
    {t:"Queimadores de gordura", tag:"Não", lvl:"no", dose:"—", when:"—", b:"Ou é cafeína cara, ou é coisa que não funciona, ou faz mal. A gordura perde-se com o défice, a proteína e o treino. Nenhuma cápsula muda isso."},
    {t:"Pré-treinos em pó", tag:"Não precisas", lvl:"no", dose:"—", when:"—", b:"São cafeína (muitas vezes 200–300 mg, demasiado) com corantes e beta-alanina, que dá formigueiro. Um café e uma banana fazem o mesmo. Se ainda assim quiseres, meia dose e nunca depois das 15h."}
  ],
  supNote: "Se estiveres grávida, a amamentar, a tomar medicação ou tiveres alguma condição de saúde, valida com a médica antes de começar qualquer suplemento. Compra marcas com testes de terceiros (Informed Sport, NSF, Cologne List).",
  meals: [["pa","Pequeno-almoço"],["al","Almoço"],["ja","Jantar"],["sn","Snack"],["pos","Pós-treino"],["doce","Doce saudável"]],
  recipes: [
    {n:"Papas de aveia proteicas", img:"1686344234276-dc3ac6f284ff", m:"pa", min:8, kcal:380, prot:30, ing:["50 g de aveia","200 ml de leite ou bebida vegetal","1 scoop de whey (30 g) ou 150 g de iogurte grego","1 banana ou punhado de frutos vermelhos","canela"], st:["Cozinha a aveia com o leite em lume brando 4 a 5 minutos, a mexer.","Tira do lume, deixa arrefecer 1 minuto e mistura a whey (se puseres com o lume ligado fica grumosa).","Cobre com fruta e canela."], tip:"Faz de véspera com iogurte em vez de cozinhar: aveia + iogurte + leite no frigorífico (overnight oats)."},
    {n:"Ovos mexidos com espinafres e pão", img:"1687630433865-f86f07be989a", m:"pa", min:8, kcal:360, prot:26, ing:["2 ovos + 2 claras","mão cheia de espinafres","1 fatia de pão integral ou de centeio","1 c. chá de azeite","sal, pimenta"], st:["Salteia os espinafres no azeite 1 minuto.","Junta os ovos batidos, lume brando, mexe devagar até cremosos.","Serve sobre o pão torrado."], tip:"Junta 30 g de queijo fresco ou 1/4 de abacate se precisares de mais gordura boa."},
    {n:"Iogurte grego, granola e fruta", img:"1692071106919-01bc0b9b0919", m:"pa", min:3, kcal:320, prot:24, ing:["200 g de iogurte grego magro ou skyr","30 g de granola pouco açucarada","fruta à escolha","1 c. chá de sementes de chia"], st:["Põe tudo numa taça, por camadas.","Se o iogurte for muito ácido, 1 c. chá de mel."], tip:"É também um bom pós-treino."},
    {n:"Panquecas de banana e aveia", img:"1528207776546-365bb710ee93", m:"pa", min:12, kcal:340, prot:22, ing:["1 banana madura","2 ovos","40 g de aveia","1 c. chá de fermento","canela","óleo de coco ou spray para untar"], st:["Tritura tudo (ou esmaga a banana e mistura à mão).","Frigideira antiaderente em lume médio, colheradas pequenas, 2 minutos por lado.","Serve com iogurte e fruta."], tip:"Faz o dobro e guarda no frigorífico; aquecem em 30 segundos."},
    {n:"Bowl de arroz, frango e legumes", img:"1679279726946-a158b8bcaa23", m:"al", min:20, kcal:480, prot:40, ing:["130 g de peito de frango","70 g de arroz (peso cru) ou 150 g cozido","brócolos, courgette, pimento","1 c. sopa de azeite","alho, paprica, limão"], st:["Corta o frango em tiras, tempera com paprica, alho e sal.","Grelha em frigideira quente 6 a 8 minutos.","Salteia os legumes 4 minutos. Monta com o arroz e rega com limão."], tip:"Cozinha 3 doses ao domingo. Aguenta 3 dias no frigorífico."},
    {n:"Salada de atum, grão e ovo", img:"1604909052743-94e838986d24", m:"al", min:10, kcal:430, prot:38, ing:["1 lata de atum ao natural","150 g de grão cozido","1 ovo cozido","tomate, pepino, cebola roxa, rúcula","1 c. sopa de azeite, vinagre, orégãos"], st:["Mistura tudo numa taça grande.","Tempera e serve. Sem cozinhar."], tip:"Troca o atum por salmão de lata ou sardinha para variar."},
    {n:"Wrap de peru e húmus", img:"1646530208887-8a791bff4701", m:"al", min:6, kcal:400, prot:30, ing:["1 tortilha integral","100 g de peito de peru fatiado","2 c. sopa de húmus","alface, tomate, cenoura ralada","pimenta"], st:["Barra a tortilha com húmus.","Distribui o peru e os vegetais, enrola apertado.","Corta ao meio."], tip:"Bom para levar para o trabalho; embrulha em papel vegetal."},
    {n:"Omelete de legumes com salada", img:"1677844592730-ce9c936d8f1a", m:"al", min:10, kcal:350, prot:26, ing:["3 ovos","cogumelos, pimento, cebola","30 g de queijo ralado (opcional)","salada verde","1 c. chá de azeite"], st:["Salteia os legumes 3 minutos.","Junta os ovos batidos, tapa, lume brando 4 minutos.","Dobra e serve com salada."], tip:"Com uma fatia de pão integral fica uma refeição completa de dia de treino."},
    {n:"Salmão no forno com batata-doce", img:"1519708227418-c8fd9a32b7a2", m:"ja", min:25, kcal:520, prot:36, ing:["150 g de salmão","200 g de batata-doce","espargos ou feijão-verde","1 c. sopa de azeite","limão, alho, ervas"], st:["Batata-doce em cubos com metade do azeite, forno a 200 °C 15 minutos.","Junta o salmão e os legumes ao tabuleiro, mais 10 a 12 minutos.","Limão por cima e serve."], tip:"Um tabuleiro só, quase sem loiça."},
    {n:"Peito de peru com puré de couve-flor", m:"ja", min:20, kcal:380, prot:42, ing:["150 g de bife de peru","300 g de couve-flor","1 c. sopa de iogurte grego","alho, noz-moscada","salada ou legumes salteados"], st:["Coze a couve-flor 10 minutos, escorre bem, tritura com iogurte, alho e noz-moscada.","Grelha o peru 3 a 4 minutos por lado.","Serve com o puré e legumes."], tip:"O puré de couve-flor tem 1/4 das calorias do puré de batata e sabe quase igual."},
    {n:"Chili de peru e feijão", m:"ja", min:30, kcal:450, prot:38, ing:["150 g de carne de peru picada","1 lata de feijão vermelho","1 lata de tomate pelado","cebola, alho, pimento","cominhos, paprica, malagueta"], st:["Refoga cebola e alho, junta a carne e sela.","Junta pimento, tomate, especiarias. 15 minutos em lume brando.","Junta o feijão nos últimos 5 minutos."], tip:"Rende 3 doses e congela bem. Serve com arroz nos dias de treino, com salada nos outros."},
    {n:"Sopa de legumes com frango desfiado", m:"ja", min:30, kcal:320, prot:30, ing:["1 peito de frango","cenoura, alho-francês, courgette, abóbora","1 batata pequena","1 c. sopa de azeite","sal, coentros"], st:["Coze o frango e os legumes em água temperada 20 minutos.","Tira o frango, tritura a sopa, desfia o frango e volta a juntar.","Azeite e coentros a servir."], tip:"Jantar leve para dias de descanso ou quando o almoço foi grande."},
    {n:"Massa integral com camarão e courgette", m:"ja", min:15, kcal:470, prot:32, ing:["70 g de massa integral","150 g de camarão","1 courgette em fios ou meias-luas","alho, malagueta, limão","1 c. sopa de azeite"], st:["Coze a massa. Salteia alho e malagueta no azeite, junta o camarão 2 minutos.","Junta a courgette 2 minutos e a massa escorrida.","Raspa de limão e serve."], tip:"Metade massa, metade courgette dá volume com menos calorias."},
    {n:"Batido pós-treino", m:"pos", min:3, kcal:330, prot:32, ing:["1 scoop de whey (30 g)","1 banana","30 g de aveia","250 ml de leite ou água","gelo"], st:["Liquidificadora, 30 segundos."], tip:"Sem whey: 200 g de iogurte grego ou skyr no lugar."},
    {n:"Tosta de atum e requeijão", m:"pos", min:5, kcal:300, prot:30, ing:["2 fatias de pão integral","1/2 lata de atum","2 c. sopa de requeijão ou queijo fresco","tomate, orégãos"], st:["Mistura o atum com o requeijão.","Barra o pão torrado, tomate por cima."], tip:"Pós-treino rápido quando não há tempo para cozinhar."},
    {n:"Skyr com fruta e frutos secos", img:"1610441009633-b6ca9c6d4be2", m:"sn", min:2, kcal:220, prot:20, ing:["150 g de skyr ou iogurte grego","fruta","10 amêndoas ou nozes"], st:["Mistura e come."], tip:"O snack mais fácil de sempre. Tem no frigorífico do trabalho."},
    {n:"Húmus com palitos de legumes", m:"sn", min:5, kcal:180, prot:7, ing:["3 c. sopa de húmus","cenoura, pepino, pimento, aipo em palitos"], st:["Corta e molha."], tip:"Sacia sem pesar. Faz o húmus em casa: grão cozido, tahini, limão, alho, azeite, triturar."},
    {n:"Ovos cozidos e fruta", m:"sn", min:10, kcal:200, prot:14, ing:["2 ovos","1 peça de fruta","sal, pimenta"], st:["Coze os ovos 9 minutos, arrefece em água fria.","Guarda com casca no frigorífico até 5 dias."], tip:"Coze 6 ao domingo."},
    {n:"Gelado de banana", m:"doce", min:5, kcal:150, prot:3, ing:["2 bananas congeladas em rodelas","1 c. sopa de cacau em pó ou manteiga de amendoim","salpico de leite"], st:["Tritura as bananas congeladas até ficar cremoso (raspa as paredes 2 ou 3 vezes).","Junta o cacau ou a manteiga de amendoim."], tip:"Tem bananas cortadas sempre no congelador."},
    {n:"Mousse de chocolate e iogurte", m:"doce", min:5, kcal:200, prot:18, ing:["150 g de iogurte grego","1 c. sopa de cacau em pó","1 c. chá de mel ou adoçante","1 quadrado de chocolate negro ralado"], st:["Mistura o iogurte com o cacau e o mel até ficar liso.","Chocolate ralado por cima. 10 minutos no frigorífico."], tip:"Mata a vontade de chocolate com 18 g de proteína."},
    {n:"Maçã assada com canela", m:"doce", min:15, kcal:120, prot:1, ing:["1 maçã","canela","1 c. chá de mel","1 c. sopa de iogurte grego para servir"], st:["Corta a maçã ao meio, tira o caroço, canela e mel por cima.","Forno a 200 °C 12 minutos (ou micro-ondas 3 minutos).","Serve com iogurte."], tip:"Sabe a tarte de maçã sem a massa."}
  ]
};
